INSERT INTO districts(name) VALUES ('South America');
INSERT INTO districts(name) VALUES ('Central America');
INSERT INTO districts(name) VALUES ('North America');
INSERT INTO districts(name) VALUES ('Europe');
INSERT INTO districts(name) VALUES ('Asia');
INSERT INTO districts(name) VALUES ('Africa');
INSERT INTO districts(name) VALUES ('Africa');

INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Noel','Koch','noelkoch@elentrix.com','2016-10-09', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Dorthy','Peters','dorthypeters@elentrix.com','2019-08-19', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Tameka','Mendez','tamekamendez@elentrix.com','2016-03-23', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Catalina','Wheeler','catalinawheeler@elentrix.com','2014-08-11', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Rosetta','Stout','rosettastout@elentrix.com','2016-03-01', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Bridgett','Peck','bridgettpeck@elentrix.com','2018-06-26', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Latoya','William','latoyawilliam@elentrix.com','2018-04-14', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Leach','Parks','leachparks@elentrix.com','2015-06-05', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Howe','Manning','howemanning@elentrix.com','2017-01-31', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Sullivan','Evans','sullivanevans@elentrix.com','2018-03-17', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Ross','Perkins','rossperkins@elentrix.com','2017-01-14', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Whitley','Castaneda','whitleycastaneda@elentrix.com','2019-07-29', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Cantu','Pugh','cantupugh@elentrix.com','2015-12-16', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Mckinney','Le','mckinneyle@elentrix.com','2014-05-23', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Irma','Mcintosh','irmamcintosh@elentrix.com','2019-08-11', 1);
INSERT INTO clients(name,surname,email,create_at, district_id) VALUES ('Alyce','Harrington','alyceharrington@elentrix.com','2017-05-01', 1);